### ISSUE TITLE
is it possible to config life frame in seperated project scope?

### ISSUE THREAD

**Issue by vikbert** [jevakallio/vscode-live-frame#1]
I need to config the live frame so that I can use the life frame in different project, for example:

- vuepress project: localhost:8080
- svelte project: localhost:5000
- react project: localhost: 3000

is it possible?

**Comment by jevakallio** [comment]
Yes, you should put the configuration into your project's settings, not your global user settings. This way you can configure the url on a per-project basis:

<img width="938" alt="Screenshot 2021-02-21 at 21 28 27" src="https://user-images.githubusercontent.com/1203949/108639310-c2a80700-748b-11eb-99aa-fa84a6105fa0.png">

**Comment by vikbert** [comment]
hi, @jevakallio thx a lot. works great.
